### ISSUE TITLE
[Feature Request] Node folding

### ISSUE THREAD

**Issue by alex-titarenko** [inspirnathan/codemirror-lang-mermaid#3]
First of all, thank you so much for continue adding new diagram types support to your library!

I have a proposal/feature request to add support for node folding. This especially can be useful for "mind maps" but can be applicable to some other diagrams like "user journey" and in the future for "class diagrams", etc.

Example:
In case of Mindmap diagram type if the node has children than it can be folded.

Not sure how difficult it is to implement, but here is what I found how it's done in the official package for Markdown language:
https://github.com/codemirror/lang-markdown/blob/6c7daa5a53ea83dd89af5308c6d8d0d06a7c5880/src/markdown.ts#L12C31-L12C31

**Comment by inspirnathan** [comment]
Hi Alex!

You're very welcome! I'm glad this library has been useful to you. Yes, that's a good idea. It shouldn't be too difficult to implement.

**Comment by inspirnathan** [comment]
Hi Alex!

Code folding support has been added in release v0.4.1. Please see [this commit](https://github.com/inspirnathan/codemirror-lang-mermaid/commit/1e059db0ff236ef2175e888046548660bfdf8a2b) for details.

By default, the `mermaid` language support will set code folding to false, so it will not interfere with the other mermaid diagrams. By using `mermaid({ fold: true})`, code folding based on indentation will be enabled.

Unfortunately, it was difficult to get code folding to work only with mindmap diagrams when using the `mermaid` language support due to how the mermaid and mindmap grammar files are architected. I tried two approaches for getting automatic code folding to work with mindmap diagrams:

1. Rewriting the mindmap grammar to support new nodes that would allow code folding based on line indents and dedents, but this led to more issues.
2. Using [transactionExtender](https://codemirror.net/docs/ref/#state.EditorState^transactionExtender) to automatically detect if the mindmap diagram was currently active. However, CodeMirror expects a transaction to occur first before adding the code folding arrows in the editor which meant that code folding wouldn't become active until the user started typing something in the editor.

For now, code folding works just by adding the `fold` property inside the language support. Hope this helps!

**Comment by alex-titarenko** [comment]
@inspirnathan thank you for the implementation I really appreciate it :)

Unfortunately, I can't test it out. I'm using `mermaidLanguageDescription` instead of `mermaid` because it is used as codeLanguage inside markdown extension, and with using mermaidLanguageDescription I can't specify fold: true

**Comment by alex-titarenko** [comment]
I checked Obsidian and they have indent-based folding for all types of diagrams

<img width="714" alt="image" src="https://github.com/inspirnathan/codemirror-lang-mermaid/assets/3290313/f4f4a7cd-7a0e-4dd2-867b-1e6783e9dcef">

Note: on my screenshot you see the fold sign only near `class Duck` only because Obsidian shows the folding sign only to nodes that are hovered with the cursor, but in general it works across all types of diagrams. Obsidian is also using CodeMirror 6 behind the scenes.

Maybe it's a good idea to enable it but default to all types of diagrams in your extension?

**Comment by alex-titarenko** [comment]
ok, I think in the case of Obsidian they enable that feature for everything, not just diagrams

<img width="796" alt="image" src="https://github.com/inspirnathan/codemirror-lang-mermaid/assets/3290313/d5608b9f-34b7-4a8a-a0c1-c564bb7dac39">

also, maybe you can rename `fold` to `enableFold`?

**Comment by alex-titarenko** [comment]
Looks like the official mermaid live editor has indent-based folding for everything as well:
https://mermaid.live

<img width="530" alt="image" src="https://github.com/inspirnathan/codemirror-lang-mermaid/assets/3290313/a24e485d-2a70-47ad-8754-145e0bfcb4fa">

<img width="384" alt="image" src="https://github.com/inspirnathan/codemirror-lang-mermaid/assets/3290313/876e636f-c878-47a6-947f-73358bc0d107">

**Comment by inspirnathan** [comment]
@alex-titarenko I figured out how to add code folding only for specific diagrams after having helpful discussions with @davidmyersdev whom also uses this library.

The plan will be to let the user pass in a config object to the `mermaid` language that looks like the following:
```ts
{
  enableFold: {
    mindmap: boolean,
    pie: boolean,
    flowchart: boolean,
    sequence: boolean,
    journey: boolean 
  } | boolean
}
```
This way, the user can configure the extension per diagram, and they can also use `{enableFold: true}` to turn it on for all of them at once.

**Comment by inspirnathan** [comment]
@alex-titarenko I figured out how to add code folding only for specific diagrams after having helpful discussions with @davidmyersdev whom also uses this library.

I initially thought to let the user pass in a config object to the mermaid language that looks like the following:
```ts
{
  enableFold: {
    mindmap: boolean,
    pie: boolean,
    flowchart: boolean,
    sequence: boolean,
    journey: boolean 
  } | boolean
}
```

This way, the user can configure the extension per diagram, and they can also use `{enableFold: true}` to turn it on for all of them at once. However, it's difficult to granularly control which parts of the document get code folding without affecting the entire document state.

As an example, suppose I have the following document in the CodeMirror editor (without the backticks):
```
\`\`\`mermaid
sequenceDiagram
  A -> B
\`\`\`

\`\`\`mermaid
mindmap
  pizza
     potato
\`\`\`
```

Toggling the code folding for each mermaid diagram independently within the same document is a bit tricky. I think the most stable and most performant way to go would be to enable code folding across all documents or none of them. I'm still investigating ways to code fold the diagrams independently, but the easiest solution would be to add the `{enableFold: true}` option 😅

**Comment by alex-titarenko** [comment]
I like more the ability to enable/disable folding for all diagrams at once (no need for the toggler for individual diagrams), I would even prefer to have this feature enabled by default and for everything.
Is there any way to make it work with `mermaidLanguageDescription`? because the setting is not supported there I can't use it for now.

**Comment by inspirnathan** [comment]
Great! Yes, I have a strategy for getting the code folding working with the `mermaidLanguageDescription`. I will make an extension that can be installed, and it will automatically enable code folding when the `mermaid()` language is used as an extension and when `mermaidLanguageDescription` is used as a markdown code language.

**Comment by inspirnathan** [comment]
@alex-titarenko Please see this [commit](https://github.com/inspirnathan/codemirror-lang-mermaid/commit/621b41583ee9cc0926533b538230bc94054e1a88) for the tool you requested. By adding this extension, it will automatically add code folding based on indents throughout the entire editor, so it will be enabled for all languages, including markdown.

**Comment by inspirnathan** [comment]
@alex-titarenko Let me know if this works for you, and I'll put it in the next release 🙂

To use this extension before I create a release, copy all the code in [this file](https://github.com/inspirnathan/codemirror-lang-mermaid/blob/621b41583ee9cc0926533b538230bc94054e1a88/src/extensions/index.ts) and add it to where you're using CodeMirror. Then, you can add `foldByIndent()` to your list of your extensions. Here's an example:

```js
const view = new EditorView({
  doc: `\`\`\`mermaid
mindmap
  pizza
    potato
\`\`\``,
  extensions: [
    basicSetup,
    markdown({
      codeLanguages: [...languages, mermaidLanguageDescription],
    }),
    foldByIndent(),
  ],
  parent: document.body,
});
```

I hope this helps! Let me know if you have any more questions.

**Comment by alex-titarenko** [comment]
Hi @inspirnathan sorry for the late response, I have been backpacking.
The extension works great, except for a few scenarios.

1. 

```
requirementDiagram

    requirement test_req {
    id: 1
    text: the test text.
    risk: high
    verifymethod: test
    }

    functionalRequirement test_req2 {
    id: 1.1
    text: the second test text.
    risk: low
    verifymethod: inspection
    }
```

From the screenshot below you can see 3 findings (where I would expect only one in front of "requirementDiagram" line):
<img width="429" alt="image" src="https://github.com/inspirnathan/codemirror-lang-mermaid/assets/3290313/ae02790f-9241-423e-a1a4-332fce76c6b4">

2.
```
first line
second line (next line has only space)
 
```

<img width="370" alt="image" src="https://github.com/inspirnathan/codemirror-lang-mermaid/assets/3290313/5c76acd5-fabd-4d90-abe7-a850e0ade364">


The space will create folding even so the line does not have any actual text.

I think it may be the same issue.

**Comment by inspirnathan** [comment]
Hi @alex-titarenko. No worries! Hope you had fun backpacking! Sorry for the delay. I was sick with the stomach flu 🤒 but I'm all better now! Thanks for catching this issue. It was an easy fix. Please see [this commit](https://github.com/inspirnathan/codemirror-lang-mermaid/commit/dda58fbed035bb8fccdc891be3f46e2793a99ac6) for the updated extension. Hopefully, it works as expected now.

Edit: I updated the commit with cleaner code

**Comment by alex-titarenko** [comment]
Sorry to hear that and I'm glad you are feeling better now! Thank you for your update, those scenarios are covered now.
Just discovered another scenario.

```json
  {
   "name": "First PWA",
   "short_name": "PWA",
    
   "start_url": "/",
   "display": "standalone",
   "theme_color": "#ffffff",
   "background_color":"#ffffff",
   "icons": [
     {
       "src": "logo-512.png",
       "sizes": "512x512",
       "type": "image/png"
     }
   ]
  }
```

On the screenshot below, it folds everything before the blank line, where it should fold everything to the end
<img width="503" alt="image" src="https://github.com/inspirnathan/codemirror-lang-mermaid/assets/3290313/72747810-0050-48ce-8a29-c9f2f82194fb">

You can check that snippet in VSCode and it will fold properly there. Thank you for your work!!!

**Comment by inspirnathan** [comment]
Oops, forgot to add an additional check for an empty line. I have fixed this error in [this commit](https://github.com/inspirnathan/codemirror-lang-mermaid/commit/6c8837112aacd88079f6b2b2f8e5ea8a28638249). Let me know if this works.

**Comment by alex-titarenko** [comment]
@inspirnathan I think it works great now!!! thank you so much!!!
